#!/usr/bin/python
print("Content-type:text/html\r\n\r\n")
print('<html>')
print('<head>')
print('<title>CGI receipt</title>')
print('</head>')
print('<body>')
print('<h2>andrew</h2>')
print('</body>')
print('</html>')